name: auto-release
on:
  push:
    tags:
      # this is a glob, not a regexp
      - '[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Set up binfmt
        run: sudo update-binfmts --enable qemu-aarch64
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run ARM64 container
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker run --rm -v "${PWD}:/tmp/cockpit" misakajimmy/cockpit-arm64v8:0.1.1
          chmod 777 ./*.deb
          for file in buddy-*.deb; do
            name=$(echo $file | sed 's/^buddy-//; s/_.*\.deb$//')
            $version=${{ github.ref }}
            mv $file buddy-$name_$version_arm64.deb
          done
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Add new feature
            - Fix bug
          draft: false
          prerelease: false
      - name: Upload asset
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: cockpit
          path: ./*.deb    