name: qemu
on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Set up binfmt
        run: sudo update-binfmts --enable qemu-aarch64
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run ARM64 container
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker run --rm -v "${PWD}:/tmp/cockpit" -w /workdir misakajimmy/cockpit:arm64v8